apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kopano
spec:
  serviceName: kopano
  selector:
    matchLabels:
      app: kopano
  replicas: 1
  template:
    metadata:
      labels:
        app: kopano
    spec:
      containers:
        - name: kopano
          image: lion7/kopano
          imagePullPolicy: Always
          ports:
            - name: smtp
              containerPort: 25
            - name: http
              containerPort: 80
            - name: pop3
              containerPort: 110
            - name: imap
              containerPort: 143
            - name: https
              containerPort: 443
            - name: smtps
              containerPort: 465
            - name: smtptls
              containerPort: 587
            - name: imaps
              containerPort: 993
            - name: pop3s
              containerPort: 995
          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: cgroup
              subPath: systemd
              mountPath: /sys/fs/cgroup/systemd
              readOnly: false
            - name: run
              mountPath: /run
            - name: tmp
              mountPath: /tmp
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kopano
spec:
  selector:
    app: kopano
  type: LoadBalancer
  ports:
    - name: smtp
      port: 25
      protocol: TCP
      targetPort: smtp
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: pop3
      port: 110
      protocol: TCP
      targetPort: pop3
    - name: imap
      port: 143
      protocol: TCP
      targetPort: imap
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: smtps
      port: 465
      protocol: TCP
      targetPort: smtps
    - name: smtptls
      port: 587
      protocol: TCP
      targetPort: smtptls
    - name: imaps
      port: 993
      protocol: TCP
      targetPort: imaps
    - name: pop3s
      port: 995
      protocol: TCP
      targetPort: pop3s
